FROM python:3.10-slim

ENV PYTHONDONTWRITEBYTECODE=1
ENV PYTHONUNBUFFERED=1
ENV OPENAI_MODEL_NAME=gpt-4o
ENV OPENAI_API_KEY=default-none
ENV MODEL=openai

WORKDIR /app

COPY requirements_openai.txt .
RUN pip install --upgrade pip && pip install -r requirements_openai.txt

COPY . .

EXPOSE 5000

CMD ["python", "main.py"]
